apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-demo
  template:
    metadata:
      labels:
        app: course-demo
    spec:
      containers:
      - name: course-demo
        image: mbndocker/course-demo  # Public course game image
        ports:
        - containerPort: 80

