apiVersion: v1
kind: Service
metadata:
  name: course-demo-service
spec:
  selector:
    app: course-demo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Exposes app externally

