apiVersion: v1
kind: Service
metadata:
  name: course-demo-service
spec:
  selector:
    app: course-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposes app externally

